[Icon Theme]
Name=MinOS
Comment=MinOS Desktop icon theme
Inherits=Breeze,hicolor
Directories=16x16/apps,16x16/places,22x22/apps,22x22/places,32x32/apps,32x32/places,48x48/apps,48x48/places,64x64/apps,64x64/places,128x128/apps,128x128/places,scalable/apps,scalable/places

[16x16/apps]
Size=16
Context=Applications
Type=Fixed

[16x16/places]
Size=16
Context=Places
Type=Fixed

[22x22/apps]
Size=22
Context=Applications
Type=Fixed

[22x22/places]
Size=22
Context=Places
Type=Fixed

[32x32/apps]
Size=32
Context=Applications
Type=Fixed

[32x32/places]
Size=32
Context=Places
Type=Fixed

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[64x64/apps]
Size=64
Context=Applications
Type=Fixed

[64x64/places]
Size=64
Context=Places
Type=Fixed

[128x128/apps]
Size=128
Context=Applications
Type=Fixed

[128x128/places]
Size=128
Context=Places
Type=Fixed

[scalable/apps]
Size=256
Context=Applications
Type=Threshold

[scalable/places]
Size=256
Context=Places
Type=Threshold
